### PR TITLE
Handle MT values as NaN to avoid string comparison

### PR DESCRIPTION
**Pull request by jylee-bcm**
This change ensures that MT values are
treated consistently as NaN (Not a Number),
improving code reliability
by eliminating string comparisons.

### Current:
image

### Improved
image

### CODE REVIEW

**Review by hyunhwan-bcm — COMMENTED** [review]
I want to make sure - you have converted MT into `-1`  not `nan`, correct? The description is confusing.

**Review by hyunhwan-bcm — APPROVED** [review]
it seems there was no speed-up but LGTM 👍 

```
➜  AI_MARRVEL git:(treat_mt_as_na) ✗ nextflow log astonishing_dubinsky -f hash,name,status,realtime # nextflow_conversion branch
fa/729800       HPO_SIM COMPLETED       14s
50/928df0       INDEX_VCF       COMPLETED       4.1s
5f/fe956a       VCF_PRE_PROCESS COMPLETED       10.8s
f3/2e2876       ANNOT_PHRANK    COMPLETED       1.3s
8c/ac90c0       REMOVE_MITO_AND_UNKOWN_CHR      COMPLETED       4.5s
b8/55f23a       ANNOT_ENSMBLE   COMPLETED       6.5s
5f/a65874       FILTER_PROBAND  COMPLETED       27.7s
0f/2fbfbf       TO_GENE_SYM     COMPLETED       1.8s
ce/952893       PHRANK_SCORING  COMPLETED       2.5s
33/4f96ee       VEP_ANNOTATE    COMPLETED       4m 49s
40/14c6f9       FEATURE_ENGINEERING_PART1       COMPLETED       2m 11s
a8/8f9349       FEATURE_ENGINEERING_PART2       COMPLETED       3m 45s
68/365c46       PREDICTION      COMPLETED       4m 16s
➜  AI_MARRVEL git:(treat_mt_as_na) ✗ nextflow log goofy_bardeen -f hash,name,status,realtime # new branch
39/90e3f9       INDEX_VCF       COMPLETED       3.8s
52/14d4d0       HPO_SIM COMPLETED       13.4s
45/edf9d5       VCF_PRE_PROCESS COMPLETED       10.7s
15/de2ce0       ANNOT_PHRANK    COMPLETED       1.3s
5d/8af6eb       REMOVE_MITO_AND_UNKOWN_CHR      COMPLETED       4.6s
10/edcde8       ANNOT_ENSMBLE   COMPLETED       6.3s
48/611b8c       FILTER_PROBAND  COMPLETED       27.3s
30/31e7e1       TO_GENE_SYM     COMPLETED       1.8s
67/3c4e47       PHRANK_SCORING  COMPLETED       2.5s
98/bfc8cc       VEP_ANNOTATE    COMPLETED       4m 46s
a2/a63b87       FEATURE_ENGINEERING_PART1       COMPLETED       2m 11s
59/06e6f7       FEATURE_ENGINEERING_PART2       COMPLETED       3m 2s
01/5044a4       PREDICTION      COMPLETED       4m 14s
```

**Comment by jylee-bcm** [comment]
> I want to make sure - you have converted MT into `-1` not `nan`, correct? The description is confusing.

You are right, I assumed -1 as NaN conceptually 😅 .

**Comment by jylee-bcm** [comment]
> ```
> ➜  AI_MARRVEL git:(treat_mt_as_na) ✗ nextflow log astonishing_dubinsky -f hash,name,status,realtime # nextflow_conversion branch
> fa/729800       HPO_SIM COMPLETED       14s
> 50/928df0       INDEX_VCF       COMPLETED       4.1s
> 5f/fe956a       VCF_PRE_PROCESS COMPLETED       10.8s
> f3/2e2876       ANNOT_PHRANK    COMPLETED       1.3s
> 8c/ac90c0       REMOVE_MITO_AND_UNKOWN_CHR      COMPLETED       4.5s
> b8/55f23a       ANNOT_ENSMBLE   COMPLETED       6.5s
> 5f/a65874       FILTER_PROBAND  COMPLETED       27.7s
> 0f/2fbfbf       TO_GENE_SYM     COMPLETED       1.8s
> ce/952893       PHRANK_SCORING  COMPLETED       2.5s
> 33/4f96ee       VEP_ANNOTATE    COMPLETED       4m 49s
> 40/14c6f9       FEATURE_ENGINEERING_PART1       COMPLETED       2m 11s
> a8/8f9349       FEATURE_ENGINEERING_PART2       COMPLETED       3m 45s
> 68/365c46       PREDICTION      COMPLETED       4m 16s
> ➜  AI_MARRVEL git:(treat_mt_as_na) ✗ nextflow log goofy_bardeen -f hash,name,status,realtime # new branch
> 39/90e3f9       INDEX_VCF       COMPLETED       3.8s
> 52/14d4d0       HPO_SIM COMPLETED       13.4s
> 45/edf9d5       VCF_PRE_PROCESS COMPLETED       10.7s
> 15/de2ce0       ANNOT_PHRANK    COMPLETED       1.3s
> 5d/8af6eb       REMOVE_MITO_AND_UNKOWN_CHR      COMPLETED       4.6s
> 10/edcde8       ANNOT_ENSMBLE   COMPLETED       6.3s
> 48/611b8c       FILTER_PROBAND  COMPLETED       27.3s
> 30/31e7e1       TO_GENE_SYM     COMPLETED       1.8s
> 67/3c4e47       PHRANK_SCORING  COMPLETED       2.5s
> 98/bfc8cc       VEP_ANNOTATE    COMPLETED       4m 46s
> a2/a63b87       FEATURE_ENGINEERING_PART1       COMPLETED       2m 11s
> 59/06e6f7       FEATURE_ENGINEERING_PART2       COMPLETED       3m 2s
> 01/5044a4       PREDICTION      COMPLETED       4m 14s
> ```


We can see there's 40s of reduction on `Feature Engineering Part 2`

It's smaller than my estimation of 2 minutes, but I think it's due to the difference of the machine or the dataset.

**Comment by hyunhwan-bcm** [comment]
Never mind, I was looking for another process. So Let's close this thread.

**Pull request merged**
